### ISSUE TITLE
README title and incorrect links

### ISSUE THREAD

**Issue by jbrucker** [thanidacwn/ku-polls-2022#1]
The links in README.md go to another repository, not your wiki.
The title should not be "ku-polls".  Use a descriptive title.

**Comment by jbrucker** [comment]
When you close an issue, especially an issue opened by someone else,
you should write a comment to explain why you are closing it.
Sometimes just "Fixed." is enough. In other cases you should say what you did.

**Comment by thanidacwn** [comment]
Thank you for the suggestion, I will explain why I closing it in the next issue.
